apiVersion: v1
kind: Service
metadata:
  name: customwear
  labels:
    app: customwear
spec:
  selector:
    app: customwear
  ports:
    - name: http
      port: 80
      targetPort: 4300
  type: ClusterIP
